### ISSUE TITLE
Update dependency on bazel_skylib

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_proto#101]
Bazel CI for Bazel@HEAD and rules_proto is currently [failing](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2211#f6e29aaa-a080-46d9-a5ed-c70a7ad7ea48), indicating an upcoming change to Bazel will break rules_proto.

This is because rules_proto depends on a version of bazel_skylib which is incompatible with upcoming Bazel changes. rules_proto should updates its version of bazel_skylib.

As a temporary workaround, one could set --incompatible_disable_depset_items=false to defer this upcoming bazel incompatibility.

**Comment by Yannic** [comment]
Thanks for reporting! I think we haven't upgraded `bazel_skylib` (+ other dependencies) in a while, so we should do that.

I'll be on vacation for the next few days, so if anyone wants to send a PR for it, go for it. Otherwise I'll send a change later next week.

**Comment by shaldengeki** [comment]
Looks like this was bumped in https://github.com/bazelbuild/rules_proto/pull/104 -- is this still necessary or desirable?

**Comment by Clement-Jean** [comment]
Could we update to 1.3.0? I can make a PR if you are ok with it
