### ISSUE TITLE
Bump zlib version to 1.2.12

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/rules_proto#118]
According to https://zlib.net/
```
Due to the bug fixes, any installations of 1.2.11 should be replaced with 1.2.12.
```
We need to bump the zlib version in the repo

PR: https://github.com/bazelbuild/rules_proto/pull/117

**Comment by caseyduquettesc** [comment]
zlib 1.2.11 was pulled it seems
https://zlib.net/zlib-1.2.11.tar.gz 404's for me

**Comment by ThomasCJY** [comment]
PR: https://github.com/bazelbuild/rules_proto/pull/117 merged
