### ISSUE TITLE
Incompatible with protobuf-cpp 3.21.0+

### ISSUE THREAD

**Issue by SanjayVas** [bazelbuild/rules_proto#136]
`PROTOBUF_MIN_PROTOC_VERSION` was updated to `3021000`. The latest rules_proto release is still using protoc 3.20.0. The latest protobuf-cpp is 3.25.1.

**Comment by SanjayVas** [comment]
Note sure about the priority here. This locks users of rules_proto to a protobuf version that's 6 releases behind and months old. As the official protobuf rules for Bazel, there should be a release policy that requires it to not lag too far behind protobuf releases.

**Comment by comius** [comment]
The update should not be hard to do. We're accepting community contributions.

**Comment by comius** [comment]
Thanks to @sagmor, the release was updated in https://github.com/bazelbuild/rules_proto/pull/139
