### ISSUE TITLE
Hash mismatch in rules_proto 5.3.0-21.5

### ISSUE THREAD

**Issue by lgalfaso** [bazelbuild/rules_proto#153]
It looks like https://github.com/bazelbuild/rules_proto/commit/f371ed34ed7f1a8b83cc34ae96db277e0ba4fcb0 did not make it into the release rules_proto 5.3.0-21.5, so running `rules_proto_dependencies()` with this release fails.

**Comment by avagin** [comment]
Cc: @kotlaja

**Comment by comius** [comment]
This was fixed with a new release.
