### ISSUE TITLE
Allow enforcement of no-unused-imports

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_proto#159]
rules_proto (well, probably the native code in Bazel) prints

```
INFO: From Generating Descriptor Set proto_library //foo/v1:foo_proto:
foo/v1/foo.proto:19:1: warning: Import foo/v1/other.proto is unused.
```

I'd like to enforce no backsliding, so promote this to an error. One way to do that would be a linter (e.g. `buf_lint_test`, if https://github.com/bufbuild/rules_buf/issues/32 were fixed). But it would be easier to run on CI with something like `bazel build --@rules_proto//proto:unused_imports=error //...`

@Yannic  WDYT?

**Comment by Yannic** [comment]
Looks reasonable! Probably needs to be possible to opt-in/out on a target or package level though (because googleapis is a huge offender of unused imports).

May require a change in `protoc` to make this an error

**Comment by alexeagle** [comment]
Note, this is supported by https://buf.build/docs/build-systems/bazel#buf-lint-test now. I don't think we need linters included in the baseline proto ruleset.
