### ISSUE TITLE
Why not use https://github.com/stackb/rules_proto

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/rules_proto#16]
https://github.com/stackb/rules_proto is an existing library that already has a lot of the features that this rules_proto repo should have.

It is built on top of aspects and does not use bind() anymore.

Maybe that is a good place to borrow things from.

**Comment by qzmfranklin** [comment]
I saw that this repo is used by [protobuf](https://github.com/protocolbuffers/protobuf).

I'd say it is rather unfortunate that the proto-grpc rules are so fragmented:

https://github.com/pubref/rules_proto
https://github.com/stackb/rules_proto
https://github.com/protocolbuffers/protobuf
https://github.com/rules-proto-grpc/rules_proto_grpc

Out of these, I believe [rules_proto_grpc](https://github.com/rules-proto-grpc/rules_proto_grpc) is the future. It has the following merits:

- Properly use Bazel concepts such as aspects, rules and repository rules to standardize and simplify the writing of proto and grpc rules.
- Yes, it supports grpc plugins in a very native manner.
- It already contains almost all proto-grpc related stuff that one can possibly find. It makes sense to expand on something that's already this large.
- It is written by people who worked on proto-grpc-bazel rules before. Many lessons are well learned and they are doing it very well this time.

**Comment by Yannic** [comment]
Thank you for your concerns. We disagree.

This repo contains replacements for (currently) native rules and providers, and tools for writing `<lang>_proto_library` rules. It will not contain any actual `<lang>_proto_library`. They'll either live in `rules_<lang>`, or in `stackb/rules_proto` / `rules-proto-grpc/rules_proto_grpc`.

**Comment by qzmfranklin** [comment]
I see, and I agree now.

Also, I was wrong in saying that stackb was using aspects. They are not. I'd wish this repo does the right thing by properly using aspects. There are many issues associated with not using aspects or not properly. I don't know when stackb will get fully ramped up with it.

I generally believe that Bazel rules for proto and grpc are a mess. Happy with the direction you brought up.
