### ISSUE TITLE
Wrong checksum rules_proto 5.3.0-21.7

### ISSUE THREAD

**Issue by thedoctar** [bazelbuild/rules_proto#162]
The workspace file for https://github.com/bazelbuild/rules_proto/releases/tag/5.3.0-21.7 contains the wrong checksum. The checksum written is dc3fb206a2cb3441b485eb1e423165b231235a1ea9b031b4433cf7bc1fa460dd, but downloading the file and using sha256sum shows it's actually 84581391956550f11673a72054248f15c957a70744d23fcc7d03a18de33cbfd1.

**Comment by Yannic** [comment]
This was due to a change from GitHub where the checksum of archives changed: https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/. They reverted the change, so the old checksum should work again.
