### ISSUE TITLE
protoc is dynamically linked

### ISSUE THREAD

**Issue by malt3** [bazelbuild/rules_proto#163]
Hello, I am trying to use bazel as a hermetic build environment. While doing so, I noticed that rules_proto fails on hermetic environments (like nixOS).

I tracked this down to protoc.exe downloaded by the ruleset being a dynamically linked binary that depends on the following:

```shell-session
ldd /home/USER/.cache/bazel/_bazel_USER/f83094fca0f0f2ee3451f9caccc3e2f4/execroot/__main__/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf_protoc_linux_x86_64/protoc.exe
        linux-vdso.so.1 (0x00007fffb5bb3000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f3627ff3000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f3627f13000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f3627c00000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3627ef9000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f3627800000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/69b7kmzzfjfxz0qaia9k60y201zp007i-glibc-multi-2.35-224/lib/ld-linux-x86-64.so.2 (0x00007f3627ffa000)
```

While I understand that it may not be a primary concern of rules_proto to support NixOS and similar environments, I would like to know if you are interested in one of the following:

- Ship all libraries that protoc depends on
- Provide a static protoc

EDIT:

[I also created an upstream issue on the protobuf repo](https://github.com/protocolbuffers/protobuf/issues/12063)

**Comment by comius** [comment]
Dynamic linking is more related to protoc and C++ toolchain. Either protoc repo needs to provide `cc_binary` with `linkstatic` set or you modify the repo yourself.
