### ISSUE TITLE
py_proto_library failed with 'proto_common' value has no field or method 'ProtoLangToolchainInfo'

### ISSUE THREAD

**Issue by sfc-gh-smao** [bazelbuild/rules_proto#166]
I hit the following error when using the new `py_proto_library` rule.

Here's the error.

```
ERROR: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_smao/293c187e0e1a4f1b15cf7560b71a752c/external/rules_python/python/private/proto/py_proto_library.bzl", line 20, column 38, in <toplevel>
                ProtoLangToolchainInfo = proto_common.ProtoLangToolchainInfo
Error: 'proto_common' value has no field or method 'ProtoLangToolchainInfo'
```

Here's the code that I have:

```
load("@rules_python//python:proto.bzl", "py_proto_library")

proto_library(
    name = "foo_proto",
    srcs = ["foo.proto"],
)

py_proto_library(
    name = "foo_proto_py_pb2",
    deps = [":foo_proto"],
)
```

**Comment by sfc-gh-smao** [comment]
cc: @comius

**Comment by Mizux** [comment]
two questions: which version did you use of modules:
0. bazel version ?
1. rules_python ?
2 rules_proto ?

My 2 cents dev note: saw it once when using on archlinux the current configuration:
* bazel: 6.0.0
* rules_python: 0.20.0
  ```bazel
  git_repository(
    name = "rules_python",
    tag = "0.20.0",
    remote = "https://github.com/bazelbuild/rules_python.git",
  )
  ```
* rules_proto: nothing (i.e. default one provided by bazel ?) 

then i tried to use rules_proto last release
```bazel
git_repository(
    name = "rules_proto",
    tag = "5.3.0-21.7",
    remote = "https://github.com/bazelbuild/rules_proto.git",
)
```
and this problem just gone... (currently crashing in another way and investigating...)

**Comment by comius** [comment]
`py_proto_library` only works with Bazel >=6.0.0 and rules_proto >= 5.3.0-21.7.

`native.proto_library` is deprecated, please use `proto_library` from this repository.
