### ISSUE TITLE
Virus detected in dependency protoc-21.7-win32.zip

### ISSUE THREAD

**Issue by ekhabarov** [bazelbuild/rules_proto#171]
Hi, 

for dependency file [protoc-21.7-win32.zip](https://github.com/bazelbuild/rules_proto/blob/master/proto/private/dependencies.bzl#L89-L95) with hash `1e3856cc5fc5074e566c7b8da90f74d2b5b6a80e3df9eafb4a86f7bb8ab32772` VirusTotal [detects a virus](https://www.virustotal.com/gui/file/1e3856cc5fc5074e566c7b8da90f74d2b5b6a80e3df9eafb4a86f7bb8ab32772/detection) by file hash. 
<img width="1317" alt="VT" src="https://user-images.githubusercontent.com/2721921/235760497-e930eafb-e17d-48f3-a41c-431367f49ac0.png">

**Comment by comius** [comment]
This seems to be a false positive.
