### ISSUE TITLE
rules_proto is failing with latest Bazel release 6.2.1 in CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_proto#173]
rules_proto is failing with latest Bazel release 6.2.1

**Reference** : https://buildkite.com/bazel/rules-proto/builds/1692

**Platforms** : Ubutu, MacOS, Windows.
**Logs**:

```
//tests/rules/proto_descriptor_set:proto_descriptor_set_test             FAILED
``` 
**Steps** : 
```
git clone https://github.com/bazelbuild/rules_proto.git
export USE_BAZEL_VERSION=6.2.1
bazel test //...

```
CC @mai93

**Comment by sgowroji** [comment]
rules\_proto Downstream CI pipeline is green now! We can close this issue now.

**Comment by comius** [comment]
Fixed.
