### ISSUE TITLE
Bazel dependency mirror URLs are invalid

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_proto#19]
Currently there are some dependency URLs in https://github.com/bazelbuild/rules_proto/blob/9cd4f8f1ede19d81c6d48910429fe96776e567b1/proto/private/dependencies.bzl#L48 that return 404s

Such as https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/166a046a27e118d578127759b413ee0b06aca3cd.tar.gz

**Comment by Yannic** [comment]
The following script uploads the missing files to bazel-mirror.
I don't have write permissions to that gcs, somebody else has to take this on.

```shell
#!/bin/bash

set -euo pipefail

# Create a temp directory to hold the versioned tarball,
# and clean it up when the script exits.
tmpdir="$(mktemp -d)"
function cleanup {
  rm -rf "$tmpdir"
}
trap cleanup EXIT

function upload {
  local file="$1"

  echo "Downloading https://${file}"
  curl -L --fail --output "${tmpdir}/archive" "https://${file}"

  echo "Uploading https://${file} to https://mirror.bazel.build/${file}"
  gsutil cp -n "${tmpdir}/archive" "gs://bazel-mirror/${file}"

  rm -rf "${tmpdir}/archive"
}

upload "github.com/protocolbuffers/protobuf/archive/c132a4aa165d8ce2b65af62d4bde4a7ce08d07c3.tar.gz"
upload "github.com/bazelbuild/rules_cc/archive/401380cd2279b83da0dcb86ecbac04a04805405b.tar.gz"
upload "github.com/bazelbuild/rules_java/archive/166a046a27e118d578127759b413ee0b06aca3cd.tar.gz"
upload "github.com/bazelbuild/rules_python/archive/4b84ad270387a7c439ebdccfd530e2339601ef27.tar.gz"
```

**Comment by Yannic** [comment]
To avoid this error with future changes in `dependencies.bzl`, we should add a test that verifies all urls are valid.

/label `enhancement` 
/assign @Yannic

**Comment by Yannic** [comment]
Sorry for the delay!

@meteorcloudy @laurentlb @jin Could you please upload these files to bazel mirror? Thank you in advance!

  - https://github.com/protocolbuffers/protobuf/archive/c132a4aa165d8ce2b65af62d4bde4a7ce08d07c3.tar.gz 
  - https://github.com/bazelbuild/rules_cc/archive/401380cd2279b83da0dcb86ecbac04a04805405b.tar.gz 
  - https://github.com/bazelbuild/rules_java/archive/166a046a27e118d578127759b413ee0b06aca3cd.tar.gz 
  - https://github.com/bazelbuild/rules_python/archive/4b84ad270387a7c439ebdccfd530e2339601ef27.tar.gz

**Comment by meteorcloudy** [comment]
Done, the following links should be available:
"https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/c132a4aa165d8ce2b65af62d4bde4a7ce08d07c3.tar.gz",
"https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/401380cd2279b83da0dcb86ecbac04a04805405b.tar.gz",
"https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/166a046a27e118d578127759b413ee0b06aca3cd.tar.gz",
"https://mirror.bazel.build/github.com/bazelbuild/rules_python/archive/4b84ad270387a7c439ebdccfd530e2339601ef27.tar.gz",

**Comment by hlopko** [comment]
What's left to do in order to close this issue? Yannic, do you consider adding the test as part of it?

**Comment by Yannic** [comment]
I considered adding a test but got worried that the network dependency makes it flaky and decided not to.

I don't have special permissions for this repo so I'll let others close this issue.
