### ISSUE TITLE
googleapis pull request related to rules_proto

### ISSUE THREAD

**Issue by pedrobisp** [bazelbuild/rules_proto#20]
Sorry to put this here, I know it belongs to the googleapi repositories - but I didn't find a way to reach the maintainers. I posted this https://github.com/googleapis/googleapis/pull/578 to prepare it for Bazel 1.0. We tested all incompatible flags on our end but are blocked by https://github.com/googleapis/googleapis/

Could you reach the maintainers and make them aware of this issue?

**Comment by Yannic** [comment]
@hlopko @lberki @laurentlb Can one of you handle this?

**Comment by hlopko** [comment]
I'll see what I can do.

**Comment by hlopko** [comment]
This took a while, but here we go: https://github.com/googleapis/googleapis/commit/bc76ffd87360ce1cd34e3a6eac28afd5e1efda76 :)
