### ISSUE TITLE
6.0.0 release candidates need instructions to import protoc

### ISSUE THREAD

**Issue by shaldengeki** [bazelbuild/rules_proto#204]
I recently tried to use 6.0.0rc1 and rc2, following the bzlmod instructions in [the release notes](https://github.com/bazelbuild/rules_proto/releases/tag/6.0.0-rc2), and discovered that this regressed the version of protoc I was using:

[Gist of setup here.](https://gist.github.com/shaldengeki/d7aede78871a6c31cb01e27ca1671bf8)
```
[libprotobuf WARNING external/protobuf~3.19.6/src/google/protobuf/compiler/parser.cc:649] No syntax specified for the proto file: example.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
example.proto:1:1: Expected top-level statement (e.g. "message").
Target //:example_proto failed to build
```

Note the `protobuf~3.19.6` above. Reverting back to [the prior release](https://registry.bazel.build/modules/rules_proto/5.3.0-21.7) gets me back to protoc 21.7.

I suspect this is because the plan for 6.0.0 is to expect users to pin their own version of protoc as part of the toolchain-ization of `rules_proto`, [as per this document.](https://docs.google.com/document/d/1CE6wJHNfKbUPBr7-mmk_0Yo3a4TaqcTPE0OWNuQkhPs/edit#heading=h.kk44cvehjrvz) Still, this is unexpected behavior (a breaking change, I'd argue), and the release notes for 6.0.0rc* should at a minimum call this out, and specify:
- that you are expected to mount `com_google_protobuf` yourself explicitly, and how to do it,
- what the expected protoc version is, without pinning

FYI @thesayyn

**Comment by alexeagle** [comment]
I updated the release notes for https://github.com/bazelbuild/rules_proto/releases/tag/6.0.0-rc3 which I'll copy across to the 6.0.0 final. I don't think any code changes are needed for this, as we don't want subsequent releases to still include notes about upgrading from earlier 5.x.
