### ISSUE TITLE
`import_prefix` only works when setting `strip_import_prefix=""` on targets defined in external dependency

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/rules_proto#21]
# Problem
protoc compilation fails when building a `proto_library` target defined in an external dependency which uses the `import_prefix` parameter.

# Expected behavior
Descriptor set compiles successfully.

# Workaround
Set `strip_import_prefix=""`

# Repro case
See .zip file. TL;DR Create `local_repository` with a single proto file defining at least one message, and add a `proto_library` target which uses the `import_prefix` parameter. 

[bazel-repro-strip_import_path.zip](https://github.com/bazelbuild/rules_proto/files/3626936/bazel-repro-strip_import_path.zip)

## Repro environment
Windows 10, Linux, Bazel 0.29.1 

# Related issues
https://github.com/bazelbuild/bazel/issues/8030

**Comment by Yannic** [comment]
I'll look into it

//cc @hlopko we talked earlier about valid uses of `strip_import_prefix=""`.

**Comment by RNabel** [comment]
@Yannic did you get anywhere with this? Do you have a rough timeline?

**Comment by Yannic** [comment]
Sorry for the delay. I can reproduce it with 0.28/0.29, but not with 1.0.
Can you confirm updating to Bazel 1.0 (rc5) works for you?

```
$ export USE_BAZEL_VERSION=last_rc
$ bazelisk version
Bazelisk version: development
Starting local Bazel server and connecting to it...
Build label: 1.0.0rc5
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 2 08:34:39 2019 (1570005279)
Build timestamp: 1570005279
Build timestamp as int: 1570005279
$ bazelisk build @proto_dep//...
INFO: Writing tracer profile to '/private/var/tmp/_bazel_yannic/6a9396812ccdb793e492078c3655810c/command.profile.gz'
INFO: Invocation ID: 95bddefc-a0e5-4652-a359-76adff45e1fc
INFO: Analyzed 2 targets (17 packages loaded, 547 targets configured).
INFO: Found 2 targets...
INFO: Elapsed time: 9.796s, Critical Path: 0.91s
INFO: 185 processes: 185 remote cache hit.
INFO: Build completed successfully, 190 total actions
```

**Comment by RNabel** [comment]
Yep, this is working on 1.0 :tada: Thanks for looking into this :)
