### ISSUE TITLE
Provide rule to collect transitive closure of descriptors into one file

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/rules_proto#45]
The descriptor set created by `proto_library` only includes descriptors from direct sources. Adding `--include_imports` is viable because it's said to have huge implications on the descriptor-size, which is problematic for large proto-graphs (https://github.com/bazelbuild/bazel/issues/4201#issuecomment-350841732).

As pointed out in, e.g., https://github.com/bazelbuild/bazel/issues/4201, some tools require descriptor sets that include all dependencies. It would be nice to provide a Starlark rule that collects the transitive descriptors or a `proto_library` target and concatenates them.

//cc @prestonvanloon

**Comment by htuch** [comment]
FWIW, we (Envoy) have built a rule that does this, see https://github.com/envoyproxy/envoy/blob/master/tools/type_whisperer/file_descriptor_set_text.bzl. It would be great to have this built-in to `rules_proto` though. Feel free to borrow from this if you want to upstream a PR.
