### ISSUE TITLE
Documentation of rules_proto

### ISSUE THREAD

**Issue by artemyarulin** [bazelbuild/rules_proto#50]
Hi, README tells to check documentation at https://docs.bazel.build/versions/master/be/overview.html which has a link to https://docs.bazel.build/versions/master/be/protocol-buffer.html which has deprecated message for all rules and advice to check https://github.com/bazelbuild/rules_proto which has a README, GOTO 1;

**Comment by Yannic** [comment]
Sorry for the slow response.

We do not have generated docs for the rules in this repo yet, hence the reference to https://docs.bazel.build/versions/master/be/protocol-buffer.html. `rules_proto` is intended to be a drop-in replacement, so the two rulesets follow the exact same API. Just make sure to include the load statement in the BUILD file(s).

We should clarify the documentation in the readme!

**Comment by artemyarulin** [comment]
Yeah, thanks, later on I've found your response in https://github.com/bazelbuild/rules_proto/issues/18#issuecomment-523842651 which helped me a lot, everything works just fine.

Thanks for your response and this project 👍

**Comment by thesayyn** [comment]
fixed by #186
