### ISSUE TITLE
Generate Protos from Upstream JARs

### ISSUE THREAD

**Issue by naturalwarren** [bazelbuild/rules_proto#55]
Some services and libraries publish JARs with `.proto` files only. It would be nice if `rules_proto` would handle generating Java classes from proto only JAR files. One of the original motivations behind this pattern was to avoid dependency conflicts between consumers and producers of `.proto` files.

Tools like the Gradle Protobuf Plugin make this a breeze. See the ["Protos in Dependencies"](https://github.com/google/protobuf-gradle-plugin#protos-in-dependencies) section of the plugin.

Would `rules_proto` support this?

**Comment by Yannic** [comment]
On first sight, it looks like we'd need to read the content of the `.jar` when creating `ProtoInfo` (i.e. during analysis). If the `.jar` is generated by another action, we'd need to execute that action before finishing analysis, which isn't really compatible with Bazel (and even if it is possible, has an impact on analysis scalability).

I'll leave this open for now in case someone has an idea how to realize this, but I think it's unlikely to happen. Sorry.

**Comment by comius** [comment]
True, you can't read content of .jar file during analysis where you'd need at minimum the names of .proto files (otherwise you don't know what file names to generate).

Bazel can only be fast and incremental when it knows dependencies among .proto files. It performs best when a single .proto file corresponds to a single proto_library target.

**Comment by plaird** [comment]
I created a simple macro to accomplish this task, and published it in case it helps others.

*proto_extract* example: https://github.com/salesforce/bazel-demo/tree/main/other_usecases/java/proto-java-srcjar
