### ISSUE TITLE
Support --include_source_info in native proto_library

### ISSUE THREAD

**Issue by htuch** [bazelbuild/rules_proto#56]
It's useful to be able to specify an optional inclusion of `source_code_info` in the proto descriptors generated by `proto_library`, for the purpose of documentation generation tools etc. I was working on an aspect that used the `proto_library` output descriptors, and this is stripped away. It's useful to strip by default, but it would be also good to have a param to `native.proto_library` that allows us to specify targets that provide the source code info.

**Comment by Yannic** [comment]
Duplicating into bazelbuild/bazel#9337

TL;DR: Bazel introduced `--experimental_proto_descriptor_sets_include_source_info` which passes `--include_source_info` when compiling the descriptor set of `proto_library` targets. It may become the default in the future.
