### ISSUE TITLE
Create versioned releases

### ISSUE THREAD

**Issue by jathu** [bazelbuild/rules_proto#59]
Is it possible to create versioned releases to match the protoc version being used in the dependency? This makes it easier to view the version in the WORKSPACE vs. the Git SHA.

**Comment by olekw** [comment]
I'll need a versioned release to package this for Debian, @meteorcloudy. Is that possible?

**Comment by meteorcloudy** [comment]
@comius @Yannic Any plan for making release for rules_proto?

**Comment by limdor** [comment]
Now that Bazel 4 has been released and the issue with ProtoInfo has been fixed, it would be a nice moment for a release.

**Comment by olekw** [comment]
Any progress on making a release?

**Comment by meteorcloudy** [comment]
Ping @comius @Yannic ~

**Comment by olekw** [comment]
To clarify, we don't need a "binary" release to package this in Debian. We just need a source release since we build everything from source anyway. So just a "0.0.1" release tag would suffice for our purposes.
