### ISSUE TITLE
Add roadmap for rules_proto

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/rules_proto#7]
The goal is to rewrite the Protobuf rules in Starlark and remove the native ones, but it's going to be a long way to get there. We should define how this process could look like.

**Comment by eordano** [comment]
In the meantime, we noticed you took out ts_proto_library from `rules_typescript`. May I ask why, if it's not released here already?

**Comment by Yannic** [comment]
@eordano I do not know anything about `rules_typescript` and their objectives. `rules_proto` will be the home for language-independent rules for Protobuf, so `ts_proto_library` is out of scope for this repo.

That said, `rules_typescript` doesn't seem to have any user-facing rules these days. Maybe `ts_proto_library` was moved to `rules_nodejs`? https://github.com/bazelbuild/rules_nodejs/blob/8c148667030448c00c5dde2a5215359147c44982/packages/typescript/src/index.bzl#L33

**Comment by Groxx** [comment]
Since I've so far failed to find them: where are the native ones defined?

**Comment by Yannic** [comment]
They are defined in `BazelProtoLibraryRule.java` and `ProtoLangToolchainRule.java` here: https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/proto/

**Comment by comius** [comment]
Two years after the last comment, I'll publish the roadmap shortly :)

**Comment by alexeagle** [comment]
Fixed by 3a8b1ceb68dd0fa8280f185b6edc5e8c10a129ca
