### ISSUE TITLE
Cannot Import from Another Proto File

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_proto#70]
I have two `.proto` files:
- `empty.proto`
  ```proto
  syntax = "proto3";

  package common;

  message Empty {}
  ``` 
- `message.proto`
  ```proto
  syntax = "proto3";

  package message;

  import "empty.proto";

  message SomeMessage {
    string content = 1;
    string author = 2;
  }

  service SomeService {
    rpc sendMessage(SomeMessage) returns(Empty);
  }
  ```

I import `empty.proto` into `message.proto`

My `BUILD` file looks like this:
```
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "empty_proto",
    srcs = ["empty.proto"],
)

proto_library(
    name = "message_proto",
    srcs = ["message.proto"],
    deps = [":empty_proto"],
)
```

But building the project throws those errors:
```
message.proto:13:40: "Empty" is not defined.
message.proto:5:1: warning: Import empty.proto but not used.
```
Is this a bug, or am I doing something wrong?

### I've created a small repro: 
https://github.com/flolu/rules_proto-import-repro where you can try it yourself.

**Comment by yishanhe** [comment]
@flolu since they are two different package, you may beed to use full path

```
service SomeService {
  rpc sendMessage(SomeMessage) returns(common.Empty);
}
```

**Comment by Yannic** [comment]
Protobuf doesn't allow relative imports like C/C++ does. You'll either have to use the `WORKSPACE`-relative path to import `empty.proto` or, if that's not possible for some reason, add `strip_import_prefix = "/" + package_name()` to the `proto_library` targets.
