### ISSUE TITLE
Updating to Protobuf 3.14

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/rules_proto#78]
Hi all! Any chance you'd consider an update to protobuf 3.14? 

[The Bazel Intellij/Android Studio plugin [currently seems broken](https://github.com/bazelbuild/intellij/issues/2265) on a [protobuf bug said to be fixed in 3.14](https://github.com/protocolbuffers/protobuf/issues/7827) and lack of rules_proto support for 3.14 is preventing recommending an update to the latest rules_proto.]

Thanks!
Chris
(ex-Googler)

P.S. Friendly heads also that the commit/version hash in the README is way old! Might confuse some newcomers :)

**Comment by aijingyc** [comment]
Please update the commit/version hash in the README. Thanks!

**Comment by tandel-pratik** [comment]
This PR will updates to the newest protobuf version https://github.com/bazelbuild/rules_proto/pull/88
