### ISSUE TITLE
How to import proto source from another target

### ISSUE THREAD

**Issue by neakor** [bazelbuild/rules_proto#89]
I have two targets one uses a a `genrule` to create a `proto_library` and other that needs to import the source proto file and use it.

Dependency target:
```
proto_library(
    name = "dependency_proto",
    srcs = [":dependency_proto_src"],
    strip_import_prefix = "path/to/this/dir",
    visibility = ["//visibility:public"],
)

genrule(
    name = "dependency_proto_src",
    srcs = ["@bazel_build_proto//file"],
    outs = ["bazel.proto"],
    cmd = "cp $< $@",
    visibility = ["//visibility:private"],
)
```

Dependent target:
```
proto_library(
    name = "dependent_proto",
    srcs = glob(["*.proto"]),
    strip_import_prefix = "path/to/this/dir",
    visibility = ["//visibility:public"],
    deps = [
        "//path/to/dependency/dir:dependency_proto",
    ],
)
```

Dependent proto file importing the dependency proto file:
```
import "dependency/path/bazel.proto";

message MyMessage {
  repeated blaze_query.Target targets = 1;
}
```

When I try to build this, I get the error:
```
import of "bazel2/proto" No dependencies were provided.
```

How should I properly do this?

**Comment by Yannic** [comment]
I don't see `bazel2/proto` anywhere. Can you create a repo with an example that fails and share the link?

**Comment by neakor** [comment]
@Yannic `bazel2/proto` is pulled from the `genrule` which comes from the external Bazel repo. It's basically the Bazel proto definitions.

**Comment by neakor** [comment]
NVM. The issue is that the dependent `go_proto_library` target also needs to explicitly declare the dependency `go_proto_library` in its `deps` field.
