### ISSUE TITLE
Bazel CI fails with Bazel@HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_proto#91]
Breakage example: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2091#c17c0576-e53f-40b5-8519-7b4e70af06b2

Culprit: https://github.com/bazelbuild/bazel/commit/7800ff9eb2dc0b4b3b7a2e6b8a908078f3e73d3b

Temporary solution: Run CI builds with `--incompatible_enable_exports_provider`. We'll need to follow up to fix these builds before the flag may be removed.

**Comment by c-parsons** [comment]
Temporary solution PR: https://github.com/bazelbuild/rules_proto/pull/92

**Comment by comius** [comment]
Can you upgrade rules_jvm_external used in rules_proto? It has been fixed not to use exports provider and it works with older Bazel versions as well.

**Comment by c-parsons** [comment]
Whoops, even worse, I misread the breakage and it's for https://github.com/protocolbuffers/protobuf, not rules_proto.
