### ISSUE TITLE
Update rules_cc dependency to more recent commit

### ISSUE THREAD

**Issue by gioannidis** [bazelbuild/rules_proto#95]
`rules_proto` pulls the `rules_cc` dependency at commit [`b7fe969`](https://github.com/bazelbuild/rules_cc/commit/b7fe9697c0c76ab2fd431a891dbb9a6a32ed7c3e) from 2019-07-22. This commit misses the [`action_names.bzl`](https://github.com/bazelbuild/rules_cc/blob/main/cc/action_names.bzl), which was created a month later at commit [`4a1c578`](https://github.com/bazelbuild/rules_cc/commit/4a1c578fb0e2fbc06089a3f917e3c3c840c214b4).

This outdated commit breaks integrating `rules_proto` with other repositories that rely on the `action_names.bzl`, because calling [`rules_proto_dependencies()`](https://github.com/bazelbuild/rules_proto/blob/master/proto/repositories.bzl) syncs the `rules_cc` to a commit much earlier than the current `HEAD`.

*See [this issue](https://github.com/erenon/bazel_clang_tidy/issues/8) for an example and the original motivation.*

How viable would it be to fetch the `rules_cc` at a later commit, e.g., [`4a1c578`](https://github.com/bazelbuild/rules_cc/commit/4a1c578fb0e2fbc06089a3f917e3c3c840c214b4) or later.?

**Comment by sualehasif** [comment]
Bump on this
